name: Java CI with JUnit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "@Desktop@1"
          MYSQL_DATABASE: "mydatabase"
          MYSQL_USER: "myuser"
          MYSQL_PASSWORD: "mypassword"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run JUnit tests
        run: mvn test
